name: Deployment Staging

on: 
  push: 
    branches: 
      - staging

permissions:
  contents: read

jobs:
  deployment-base:
    uses: ./.github/workflows/deployment-base.yml
    with:
      environment: staging
    secrets: inherit